micronaut:
  application:
    name: order-service
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders_user
    password: orders_pass
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE

logger:
  levels:
    com.example.order: INFO
    io.micronaut.data: DEBUG
